export const COUNTRY_MAP: Record<string, string> = {
  BJ: "Benin",
  BW: "Botswana",
  BF: "Burkina Faso",
  CM: "Cameroon",
  CG: "Republic of the Congo",
  CD: "Democratic Republic of the Congo",
  CI: "Côte d’Ivoire",
  GA: "Gabon",
  GH: "Ghana",
  KE: "Kenya",
  MW: "Malawi",
  ML: "Mali",
  NG: "Nigeria",
  RW: "Rwanda",
  SN: "Senegal",
  ZA: "South Africa",
  TZ: "Tanzania",
  TG: "Togo",
  UG: "Uganda",
  ZM: "Zambia",
};

export const CURRENCY_MAP: Record<string, string> = {
  XOF: "West African CFA franc",
  BWP: "Botswana pula",
  XAF: "Central African CFA franc",
  CDF: "Congolese franc",
  GHS: "Ghanaian cedi",
  KES: "Kenyan shilling",
  MWK: "Malawian kwacha",
  NGN: "Nigerian naira",
  RWF: "Rwandan franc",
  ZAR: "South African rand",
  TZS: "Tanzanian shilling",
  UGX: "Ugandan shilling",
  ZMW: "Zambian kwacha",
};